name: authentication_repository
description: Dart package which manages the authentication domain. Provides the Repository and a User Model
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: "^0.14.1+3"
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
